spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://218.198.180.38:3306/muxin?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8080
